### ISSUE TITLE
Code review 1.0

### ISSUE THREAD

**Issue by theaspect** [DaffPunks/software-engineering#7]
1. Экцепшен тихо подавляется https://github.com/DaffPunks/software-engineering/blame/master/src/com/god/damn/User.java#L44 так быть не должно
2. Класс нужно переписать на enum https://github.com/DaffPunks/software-engineering/blob/master/src/com/god/damn/Role.java#L4
3. Для работы битовыми масками https://github.com/DaffPunks/software-engineering/blob/master/src/com/god/damn/Cli.java#L104 используй https://docs.oracle.com/javase/7/docs/api/java/util/BitSet.html
4. Вынеси exit коды в константы https://github.com/DaffPunks/software-engineering/blob/master/src/com/god/damn/Cli.java#L181
5. Тут https://github.com/DaffPunks/software-engineering/blob/master/src/com/god/damn/Cli.java#L256 необходимы примеры в комментариях поскольку алгоритм весьма неочевиден с первого прочтения

**Comment by DaffPunks** [comment]
Done
